vagrant:
  hostname: example
#  memory: 2048
#  synced_folders:
#    HOST_DIRECTORY: GUEST_DIRECTORY
#  networks:
#    private_network:
#      ip: 192.168.50.4
vlamp:
  sites:
    # <full-domain> is the combination of the server hostname and tld.
    # E.x. "example.local"
    <full-domain>:
      host_docroot: ../docroot
      guest_docroot: /home/vagrant/docroot
      aliases:
        - alias.<full-domain>
      # Setup certificate and key for SSL. (Optional)
      # @see - (The SSL readme to create a certificate for your domain.)[assets/ssl/README.rd]
      ssl_certificate: /home/vagrant/assets/ssl/<full-domain>.cert
      ssl_certificate_key: /home/vagrant/assets/ssl/<full-domain>.key
  # E.x. "example_local"
  databases:
    - <full-domain>
utils:
  scripts:
    post-install:
      - docroot/sites/all/dstack/install.sh
    post-up:
      - docroot/sites/all/dstack/up.sh
chef:
  recipes:
    - avahi
    - default-web
    - drupal
#    - drupal::solr
    - drupal::varnish
    - utils::dev-tools
#    - utils::phpmyadmin
    - utils::scripts
      #- utils::xdebug
#  drupal:
#    solr:
#      module_path: /home/vagrant/docroot/sites/all/modules/contrib/apachesolr
# Overriding recipe attributes.
#  lamp:
#    php:
#      memory_limit: '128M'
