vagrant:
  ipaddress: 192.168.33.10
  host: example
  memory: 1024
#  synced_folders:
#    HOST_DIRECTORY: GUEST_DIRECTORY
vlamp:
  sites:
    # <hostaname> is the combination of the server host and tld.
    # E.x. "example.dstack"
    <hostname>:
      host_docroot: ../docroot
      guest_docroot: /home/vagrant/docroot
      aliases:
        - alias.<hostname>
  # E.x. "example_dstack"
  databases:
    - <hostname>
utils:
  scripts:
    post-install:
      - docroot/sites/all/dstack/install.sh
    post-up:
      - docroot/sites/all/dstack/up.sh
chef:
  recipes:
    - default-web
    - utils::dev-tools
    - utils::scripts
    - utils::xdebug
# Overriding recipe attributes.
  lamp:
    php:
      memory_limit: '256M'
