vagrant:
  hostname: example
#  memory: 2048
#  synced_folders:
#    HOST_DIRECTORY: GUEST_DIRECTORY
#  networks:
#    private_network:
#      ip: 192.168.50.4
vlamp:
  sites:
    # <hostaname> is the combination of the server host and tld.
    # E.x. "example.local"
    <full-domain>:
      host_docroot: ../docroot
      guest_docroot: /home/vagrant/docroot
      aliases:
        - alias.<full-domain>
  # E.x. "example
  databases:
    - <full-domain>
utils:
  scripts:
    post-install:
      - docroot/sites/all/dstack/install.sh
    post-up:
      - docroot/sites/all/dstack/up.sh
chef:
  recipes:
    - avahi
    - default-web
    - drupal
#    - drupal::solr
    - utils::dev-tools
    - utils::scripts
    - utils::xdebug
#  drupal:
#    solr:
#      module_path: /home/vagrant/docroot/sites/all/modules/contrib/apachesolr
# Overriding recipe attributes.
#  lamp:
#    php:
#      memory_limit: '128M'
