vagrant:
  hostname: example
  networks:
    - private_network:
       ip: 192.168.50.200
chef:
  recipes:
#    - avahi # BROKEN!
    - default-web
#    - drupal
#    - drupal::solr
#    - drupal::varnish
#    - utils::dev-tools
#    - utils::phpmyadmin
#    - utils::scripts
#    - utils::xdebug
#    - utils::webgrind
#    - utils::xhprof
#  drupal:
#    solr:
#      module_path: /home/vagrant/docroot/sites/all/modules/contrib/apachesolr
# Overriding recipe attributes.
#  lamp:
#    php:
#      version: '5.6'
#      memory_limit: '128M'
