name 'utils'
maintainer 'dStack Development Team'
maintainer_email 'delaigle.jonathan@gmail.com'
license 'Apache 2.0'
description 'Configures utilities.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '01110110.01110100'
recipe 'utils::dev-tools', 'Installs and configures development tools.'
recipe 'utils::phpmyadmin', 'Installs and confiures PHPMyAdmin.'
recipe 'utils::scripts', 'Runs specified scripts at post-install and post-up.'
recipe 'utils::solr', 'Installs and configures ApacheSolr using Jetty.'
recipe 'utils::webgrind', 'Installs and configures WebGrind.'
recipe 'utils::xdebug', 'Installs and configures xdebug.'
recipe 'utils::xhprof', 'Installs and configures Xhprof.'
depends 'git'
depends 'hipsnip-solr'
depends 'lamp'
depends 'php'
depends 'phpmyadmin'
depends 'rsync'
depends 'vim'
