name 'lamp'
maintainer 'dStack Development Team'
maintainer_email 'delaigle.jonathan@gmail.com'
license 'Apache 2.0'
description 'Install and configures the *AMP stack.'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '{{dStackVersion}}'
depends 'apt'
depends 'build-essential'
depends 'apache2'
depends 'cron'
depends 'database'
depends 'mysql'
depends 'openssl'
depends 'php'
