name             "dstack"
maintainer       "dStack Development Team"
maintainer_email "delaigle.jonathan@gmail.com"
license          "Apache 2.0"
description      "Install and configures the base components for dStack."
long_description IO.read(File.join(File.dirname(__FILE__), "README.md"))
version          "0.0.1"
depends "apt"
depends "cron"
depends "build-essential"
depends "php"
